name: Trigger auto deployment for agrani-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/agrani-api-AutoDeployTrigger-80a8ad45-0085-4c60-b176-13875c894ff6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AGRANIAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AGRANIAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AGRANIAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: agraniregistry.azurecr.io
          registryUsername: ${{ secrets.AGRANIAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AGRANIAPI_REGISTRY_PASSWORD }}
          containerAppName: agrani-api
          resourceGroup: agrani-rg-registry-1
          imageToBuild: agraniregistry.azurecr.io/agrani-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


